### ISSUE TITLE
Outlook Authentication

### ISSUE THREAD

**Issue by Alan451** [swciitg/msh-booking-portal#3]
integrate the outlook authentication

**Comment by shrihaxori** [comment]
started working

**Comment by shrihaxori** [comment]
done pls verify

**Comment by dhruvsomani** [comment]
![image](https://user-images.githubusercontent.com/13075746/126038787-d1299349-bd5e-4698-aff4-81fcf9dec7e5.png)

 @shrihaxori getting this while attempting to login.
